#!/usr/bin/env python
"""
Recover legislation_year for sections where regex parsing returned null.

These are pre-1963 legislation with nonstandard regnal year URIs generated by
LLM-based OCR — hallucinations, inconsistent formatting, freetext monarch names.

THREE-TIER APPROACH:
  Tier 1 (regex, 6 strategies):
    1. Explicit year in URI path or parenthesised text
    2. Regnal years with nonstandard separators (slash, underscore, concat)
    3. Combined reign references (Edw8and1Geo6)
    4. Broad monarch matching with subsequent numbers
    5. Broad freetext year extraction (any 4-digit year in URI)
    6. Number-before-monarch patterns (33 Vict., 5 Edw. 7.)

  Tier 2 (LLM): Azure OpenAI gpt-5-nano with monarch table in system prompt.
    Batches 25 URIs per call, medium reasoning effort. Writes to Qdrant
    continuously as batches complete.

Results (March 2026):
  Original null-year: 213,356 sections
  Tier 1 (strategies 1-4): 172,251 recovered
  Tier 2 (LLM):             ~4,889 recovered
  Tier 1 (strategies 5-6):  22,924 recovered
  Remaining null:            13,292 (genuinely unrecoverable)
  Final coverage:            99.37%

Usage:
    uv run python scripts/maintenance/fix_null_years.py                        # dry run
    uv run python scripts/maintenance/fix_null_years.py --apply                # apply all
    uv run python scripts/maintenance/fix_null_years.py --apply --tier1-only   # regex only
    uv run python scripts/maintenance/fix_null_years.py --apply --tier2-only   # LLM only
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).parent.parent))  # scripts/ directory

from dotenv import load_dotenv

load_dotenv(dotenv_path=Path(__file__).parent.parent.parent / ".env", override=True)

from _console import console, print_header, print_summary, setup_logging  # noqa: E402
from openai import AzureOpenAI  # noqa: E402
from qdrant_client import models  # noqa: E402
from rich.progress import Progress  # noqa: E402

from lex.core.qdrant_client import get_qdrant_client  # noqa: E402
from lex.legislation.models import _REGNAL_YEAR_RANGES  # noqa: E402
from lex.settings import LEGISLATION_SECTION_COLLECTION  # noqa: E402

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────

OPERATIONS_BATCH_SIZE = 200
DEFAULT_SCROLL_BATCH_SIZE = 500
MAX_RETRIES = 5
BASE_BACKOFF = 2.0
LLM_BATCH_SIZE = 25
LLM_MAX_WORKERS = 5

# Payload fields to read from each point
READ_FIELDS = ["legislation_id", "legislation_year"]

# ── Monarch alias map ─────────────────────────────────────────────────────
# Maps lowercase variants → canonical _REGNAL_YEAR_RANGES key.
# None means ambiguous (need a number suffix to disambiguate).

MONARCH_ALIASES: dict[str, str | None] = {
    # Victoria (including Latinised form from OCR)
    "victoria": "Vict", "victoriae": "Vict", "vict": "Vict", "vic": "Vict",
    # George (need number)
    "george": None,
    "geo1": "Geo1", "geo2": "Geo2", "geo3": "Geo3",
    "geo4": "Geo4", "geo5": "Geo5", "geo6": "Geo6",
    # Edward (need number)
    "edward": None,
    "edw1": "Edw1", "edw2": "Edw2", "edw3": "Edw3",
    "edw4": "Edw4", "edw5": "Edw5", "edw6": "Edw6",
    "edw7": "Edw7", "edw8": "Edw8",
    "edwvii": "Edw7",  # Romanised form from OCR
    # Henry (need number)
    "henry": None,
    "hen3": "Hen3", "hen4": "Hen4", "hen5": "Hen5",
    "hen6": "Hen6", "hen7": "Hen7", "hen8": "Hen8",
    # William (need number)
    "william": None,
    "will3": "Will3", "will4": "Will4",
    # Charles
    "charles": None,
    "cha1": "Cha1", "chas1": "Cha1", "cha2": "Cha2", "chas2": "Cha2",
    # James (including short form from Acts of English Parliament URIs)
    "james": None,
    "jas1": "Jas1", "jas2": "Jas1",  # Jas2 not in table — map to Jas1 for safety
    "ja1": "Jas1", "ja2": "Jas1",  # aep/ paths use Ja1, Ja2
    # Anne
    "anne": "Ann", "ann": "Ann",
    # Richard
    "ric2": "Ric2", "ric3": "Ric2",  # Ric3 not in table
    "richard": None,
    # Elizabeth
    "eliz1": "Eliz1", "eliz": "Eliz1", "elizabeth": None, "eliz2": "Eliz2",
    # Mary / Philip & Mary
    "mary": "Mar1", "mar1": "Mar1",
    "willandmar": "WillandMar", "willandmarsess2": "WillandMar",
    "philandmar": "Mar1", "philandmarsess": "Mar1",
}

# Build a fast lookup from canonical keys too
for key in _REGNAL_YEAR_RANGES:
    lower = key.lower()
    if lower not in MONARCH_ALIASES:
        MONARCH_ALIASES[lower] = key

# Compiled regex patterns for regnal year extraction
# Matches monarch abbreviations (case-insensitive) in URI path segments
_MONARCH_PATTERN = "|".join(
    re.escape(k) for k in sorted(_REGNAL_YEAR_RANGES.keys(), key=len, reverse=True)
)
_REGNAL_RE = re.compile(
    rf"(?i)\b({_MONARCH_PATTERN})\b"
)

# ── LLM system prompt ────────────────────────────────────────────────────

LLM_SYSTEM_PROMPT = """You are a UK legal citation expert. Given legislation URIs from legislation.gov.uk, determine the calendar year each Act was enacted.

UK legislation before 1963 uses regnal years — the year of a monarch's reign. For example, "5 & 6 Vict" means sessions 5-6 of Queen Victoria's reign (which started 1837), so 5 Vict = 1841 (1837 + 5 - 1 = 1841).

To calculate: year = monarch_reign_start + first_session_number - 1

Monarch reign start years (canonical abbreviation = start year):
Hen3=1216, Edw1=1272, Edw2=1307, Edw3=1327, Ric2=1377, Hen4=1399, Hen5=1413, Hen6=1422, Edw4=1461, Ric3=1483, Hen7=1485, Hen8=1509, Edw6=1547, Mar1=1553 (Mary I), Eliz1=1558, Jas1=1603, Cha1=1625 (Charles I), Cha2=1660 (Charles II), WillandMar=1689, Will3=1694, Ann=1702, Geo1=1714, Geo2=1727, Geo3=1760, Geo4=1820, Will4=1830, Vict=1837, Edw7=1901, Geo5=1910, Edw8=1936, Geo6=1936, Eliz2=1952.

Common patterns:
- /ukpga/Vict/44-45/12 → Victoria session 44 → 1837+44-1 = 1880
- /ukpga/Geo3/39-40/67 → George III session 39 → 1760+39-1 = 1798
- /ukla/Edw7/9/29 → Edward VII session 9 → 1901+9-1 = 1909
- Combined reigns: /Edw8and1Geo6/1/100 → use George VI session 1 → 1936+1-1 = 1936

Some URIs contain OCR artefacts like [UNCLEAR:...] — use surrounding context to infer the most likely legislation and year. Return null for year only if genuinely unrecoverable.

IMPORTANT: Respond with ONLY a JSON array, no other text. Each element:
{"uri": "<the original uri>", "year": <integer or null>, "confidence": "high"|"medium"|"low"}"""


# ── Retry helper ──────────────────────────────────────────────────────────

def _is_retryable(error: Exception) -> bool:
    error_str = str(error).lower()
    return any(term in error_str for term in ["timed out", "timeout", "connection"])


def _retry_with_backoff(operation_name: str, operation, max_retries=MAX_RETRIES):
    for attempt in range(max_retries):
        try:
            return operation()
        except Exception as e:
            if attempt == max_retries - 1 or not _is_retryable(e):
                raise
            backoff = BASE_BACKOFF * (2**attempt)
            logger.warning(
                f"{operation_name} timeout (attempt {attempt + 1}/{max_retries}), "
                f"retrying in {backoff:.0f}s..."
            )
            time.sleep(backoff)


# ── Tier 1: Regex-based parsing ──────────────────────────────────────────

def _resolve_monarch(text: str) -> tuple[str, int, int] | None:
    """Resolve a monarch string to (canonical_key, reign_start, reign_end).

    Handles both canonical abbreviations and common aliases.
    """
    lower = text.lower().strip()

    # Direct canonical match
    if lower in MONARCH_ALIASES:
        canonical = MONARCH_ALIASES[lower]
        if canonical and canonical in _REGNAL_YEAR_RANGES:
            start, end = _REGNAL_YEAR_RANGES[canonical]
            return canonical, start, end

    # Try with trailing digits: "George5" → "Geo5", "Edward7" → "Edw7"
    match = re.match(r"([a-z]+?)(\d+)$", lower)
    if match:
        name, num = match.groups()
        # Try common abbreviations
        for prefix in [name[:3], name[:4], name]:
            candidate = f"{prefix}{num}"
            if candidate in MONARCH_ALIASES:
                canonical = MONARCH_ALIASES[candidate]
                if canonical and canonical in _REGNAL_YEAR_RANGES:
                    start, end = _REGNAL_YEAR_RANGES[canonical]
                    return canonical, start, end

    return None


def _compute_year(reign_start: int, reign_end: int, session: int) -> int | None:
    """Compute calendar year from reign start and session number, with validation."""
    year = reign_start + session - 1
    if reign_start <= year <= reign_end + 1:  # +1 for edge cases at end of reign
        return year
    return None


def _try_explicit_year(uri: str) -> int | None:
    """Strategy 1: Extract explicit 4-digit year from URI path or freetext.

    Handles:
      /ukpga/1845/18
      52 & 53 Vict. c. clviii (1889)  → extracts (1889)
      S.I. 1948 No. 955               → extracts 1948
    """
    # Check for parenthesised year in freetext citations
    # Matches both "(1889)" and "(Cleveland Gas Act 1875)"
    paren_match = re.search(r"\([^)]*?(\d{4})[^)]*?\)", uri)
    if paren_match:
        year = int(paren_match.group(1))
        if 1200 <= year <= 2026:
            return year

    # Check for "S.I. YYYY" or "SI YYYY" pattern
    si_match = re.search(r"(?i)S\.?I\.?\s*(\d{4})", uri)
    if si_match:
        year = int(si_match.group(1))
        if 1200 <= year <= 2026:
            return year

    # Standard URI path segments — scan all parts
    parts = uri.split("/")
    for part in parts:
        match = re.match(r"^(\d{4})$", part)
        if match:
            year = int(match.group(1))
            if 1200 <= year <= 2026:
                return year
    return None


def _try_regnal_with_separators(uri: str) -> int | None:
    """Strategy 2: Parse regnal years with nonstandard separators.

    Handles URI-style paths:
      /Vict/44/45/...        → slash-separated session years
      /Vict_44_45/...        → underscore-separated
      /Victoria/44and45/     → freetext with "and"
      /Geo5/15/16/...        → slash-separated session for George V
      /52-53Vict/cxcvii      → session-monarch concatenated (most common!)
      /30-31-Vict/Cap.103    → session-dash-monarch with dashes
      /5-Edw-7/53            → session-dash-monarch-number

    Also handles freetext citations:
      52 & 53 Vict. c. clviii
      23 & 24 Geo. 5 c. 32
      14 Geo. 6. c. xliii
      3 & 4 Geo. 6. c. xxix
    """
    # ── Pattern A: Freetext citation "N & N Monarch. N c. ..." ──────
    # Matches: "52 & 53 Vict. c. clviii" or "3 & 4 Geo. 5 c. 32"
    freetext_re = re.compile(
        r"(\d+)\s*[&]\s*\d+\s+"           # "52 & 53 "
        r"([A-Za-z]+)\.?\s*"               # "Vict." or "Geo."
        r"(\d+)?",                          # optional monarch number "5"
        re.IGNORECASE,
    )
    match = freetext_re.search(uri)
    if match:
        session_str, monarch_name, monarch_num = match.groups()
        lookup = monarch_name.strip(".")
        if monarch_num:
            lookup = f"{lookup}{monarch_num}"
        monarch_info = _resolve_monarch(lookup)
        if monarch_info:
            _, reign_start, reign_end = monarch_info
            try:
                session = int(session_str)
                year = _compute_year(reign_start, reign_end, session)
                if year:
                    return year
            except ValueError:
                pass

    # Also: "N Monarch. c. ..." without "&" (e.g. "14 Geo. 6. c. xliii")
    single_re = re.compile(
        r"(\d+)\s+"                         # "14 "
        r"([A-Za-z]+)\.?\s*"               # "Geo."
        r"(\d+)?\.?\s*"                     # "6."
        r"c\.",                             # "c."
        re.IGNORECASE,
    )
    match = single_re.search(uri)
    if match:
        session_str, monarch_name, monarch_num = match.groups()
        lookup = monarch_name.strip(".")
        if monarch_num:
            lookup = f"{lookup}{monarch_num}"
        monarch_info = _resolve_monarch(lookup)
        if monarch_info:
            _, reign_start, reign_end = monarch_info
            try:
                session = int(session_str)
                year = _compute_year(reign_start, reign_end, session)
                if year:
                    return year
            except ValueError:
                pass

    # ── Pattern B: URI path segments ────────────────────────────────
    parts = uri.split("/")
    # Find the start index: after "id" segment for full URIs, or index 0 for short paths
    try:
        start_idx = parts.index("id") + 2  # skip "id" and type (e.g. "ukpga")
    except ValueError:
        # Short path like "ukpga/52-53Vict/..." or no "id" segment
        start_idx = 1 if len(parts) > 1 else 0

    if len(parts) <= start_idx:
        return None

    for i in range(start_idx, min(len(parts), start_idx + 5)):
        part = parts[i]

        # B1: Session-Monarch concatenated: "52-53Vict", "30-31-Vict", "5-Edw-7"
        # Also handles: "12-13Geo5", "45-46Vict", "20-21Vict"
        concat_re = re.compile(
            r"^(\d+)(?:-\d+)?[-_]?"          # "52-53" or "52" session
            r"([A-Za-z]+)[-_]?"               # "Vict" or "Edw" monarch (greedy)
            r"(\d+)?$",                       # optional monarch number "7"
            re.IGNORECASE,
        )
        concat_match = concat_re.match(part)
        if concat_match:
            session_str, monarch_name, monarch_num = concat_match.groups()
            lookup = monarch_name
            if monarch_num:
                lookup = f"{monarch_name}{monarch_num}"
            monarch_info = _resolve_monarch(lookup)
            if monarch_info:
                _, reign_start, reign_end = monarch_info
                try:
                    session = int(session_str)
                    if 1 <= session <= 70:
                        year = _compute_year(reign_start, reign_end, session)
                        if year:
                            return year
                except ValueError:
                    pass

        # B2: Underscore-separated: "Vict_44_45" or "55-56_Vict"
        if "_" in part:
            segments = part.split("_")
            # Try monarch first: "Vict_44_45"
            monarch_info = _resolve_monarch(segments[0])
            if monarch_info:
                _, reign_start, reign_end = monarch_info
                for seg in segments[1:]:
                    try:
                        session = int(seg.split("-")[0])
                        year = _compute_year(reign_start, reign_end, session)
                        if year:
                            return year
                    except (ValueError, IndexError):
                        continue
            # Try session first: "55-56_Vict"
            for seg_idx, seg in enumerate(segments):
                try:
                    session = int(seg.split("-")[0])
                    # Look for monarch in remaining segments
                    for remaining in segments[seg_idx + 1 :]:
                        monarch_info = _resolve_monarch(remaining)
                        if monarch_info:
                            _, reign_start, reign_end = monarch_info
                            year = _compute_year(reign_start, reign_end, session)
                            if year:
                                return year
                except ValueError:
                    continue

        # B3: Part is a monarch name — look at subsequent parts for session
        monarch_info = _resolve_monarch(part)
        if not monarch_info:
            # Try stripping trailing digits: "Vict44"
            strip_match = re.match(r"([A-Za-z]+?)(\d+(?:-\d+)?)$", part)
            if strip_match:
                monarch_info = _resolve_monarch(strip_match.group(1))
                if monarch_info:
                    _, reign_start, reign_end = monarch_info
                    try:
                        session = int(strip_match.group(2).split("-")[0])
                        year = _compute_year(reign_start, reign_end, session)
                        if year:
                            return year
                    except (ValueError, IndexError):
                        pass
            continue

        _, reign_start, reign_end = monarch_info

        # Look at subsequent parts for session numbers
        for j in range(i + 1, min(len(parts), i + 4)):
            next_part = parts[j]

            # "44and45", "44_45", "44-45"
            session_match = re.match(r"(\d+)(?:and|-|_|/)(\d+)", next_part)
            if session_match:
                session = int(session_match.group(1))
                year = _compute_year(reign_start, reign_end, session)
                if year:
                    return year

            # Plain number
            try:
                session = int(next_part)
                if 1 <= session <= 70:
                    year = _compute_year(reign_start, reign_end, session)
                    if year:
                        return year
                break
            except ValueError:
                if next_part.lower().startswith(("c", "ch", "cap")):
                    continue
                break

    return None


def _try_combined_reign(uri: str) -> int | None:
    """Strategy 3: Handle combined reign references.

    URI patterns:
      /Edw8and1Geo6/...        → Edward VIII & 1 George VI
      /Edw8And1Geo6/...

    Freetext patterns:
      1 Edw. 8. & 1 Geo. 6. c. lii
      1 Edw. 8 & 1 Geo. 6 c. 36
    """
    # URI path: "Edw8and1Geo6"
    combined_uri_re = re.compile(
        r"(?i)([A-Za-z]+\d?)and(\d*)([A-Za-z]+\d?)",
    )
    parts = uri.split("/")
    for part in parts:
        match = combined_uri_re.search(part)
        if match:
            _monarch1, session_str, monarch2_name = match.groups()
            monarch2_info = _resolve_monarch(monarch2_name)
            if monarch2_info:
                _, reign_start, reign_end = monarch2_info
                session = int(session_str) if session_str else 1
                year = _compute_year(reign_start, reign_end, session)
                if year:
                    return year

    # Freetext: "1 Edw. 8. & 1 Geo. 6. c."
    combined_freetext_re = re.compile(
        r"(?i)\d+\s+[A-Za-z]+\.?\s*\d+\.?\s*"  # "1 Edw. 8."
        r"[&]\s*"                                 # "&"
        r"(\d+)\s+"                               # session "1"
        r"([A-Za-z]+)\.?\s*"                      # "Geo."
        r"(\d+)?",                                # "6"
    )
    match = combined_freetext_re.search(uri)
    if match:
        session_str, monarch_name, monarch_num = match.groups()
        lookup = monarch_name.strip(".")
        if monarch_num:
            lookup = f"{lookup}{monarch_num}"
        monarch_info = _resolve_monarch(lookup)
        if monarch_info:
            _, reign_start, reign_end = monarch_info
            try:
                session = int(session_str)
                year = _compute_year(reign_start, reign_end, session)
                if year:
                    return year
            except ValueError:
                pass

    # Dash-separated combined reign: "10-Edw-7-&-1-Geo-5-ch-1"
    dash_combined_re = re.compile(
        r"(\d+)-([A-Za-z]+)-(\d+)-&-(\d+)-([A-Za-z]+)-(\d+)",
        re.IGNORECASE,
    )
    match = dash_combined_re.search(uri)
    if match:
        s1, m1_name, m1_num, s2, m2_name, m2_num = match.groups()
        # Try first monarch
        monarch_info = _resolve_monarch(f"{m1_name}{m1_num}")
        if monarch_info:
            _, reign_start, reign_end = monarch_info
            session = int(s1)
            year = _compute_year(reign_start, reign_end, session)
            if year:
                return year
        # Try second monarch
        monarch_info = _resolve_monarch(f"{m2_name}{m2_num}")
        if monarch_info:
            _, reign_start, reign_end = monarch_info
            session = int(s2)
            year = _compute_year(reign_start, reign_end, session)
            if year:
                return year

    return None


def _try_freetext_monarch(uri: str) -> int | None:
    """Strategy 4: Broad monarch matching with any extractable numbers.

    Last resort regex strategy — scan the URI for any monarch reference
    followed by numeric content.
    """
    # Join all path parts for scanning
    path_text = uri

    # Find monarch references
    for match in _REGNAL_RE.finditer(path_text):
        canonical_key = match.group(1)
        if canonical_key not in _REGNAL_YEAR_RANGES:
            # Try case-insensitive lookup
            for key in _REGNAL_YEAR_RANGES:
                if key.lower() == canonical_key.lower():
                    canonical_key = key
                    break
            else:
                continue

        reign_start, reign_end = _REGNAL_YEAR_RANGES[canonical_key]

        # Look for numbers after the monarch match
        after_monarch = path_text[match.end():]
        numbers = re.findall(r"(\d+)", after_monarch)
        for num_str in numbers[:3]:  # Check first 3 numbers
            session = int(num_str)
            if 1 <= session <= 70:
                year = _compute_year(reign_start, reign_end, session)
                if year:
                    return year

    return None


def _try_broad_year(uri: str) -> int | None:
    """Strategy 5: Extract any 4-digit year from URI freetext.

    Last-resort year extraction — scans the entire URI for year-like numbers.
    Intentionally placed last because it's the loosest pattern.

    Catches patterns missed by Strategy 1:
      1949 No. 2170
      S.R. & O. 1948 No. 845
      Carlisle Corporation Act 1904
      ukpga/28-vict-cap-xcix-1865
      Northern Ireland Statutory Rules 1951 No. 44
    """
    matches = re.findall(r"\b(1[2-9]\d{2}|20[0-2]\d)\b", uri)
    if len(matches) == 1:
        return int(matches[0])
    elif len(matches) > 1:
        # Multiple years — prefer one appearing after "Act", "No.", "S.R.", or "Rules"
        for m in re.finditer(
            r"(?:Act\s+|Rules\s+|No\.\s*|S\.R\..*?|Order.*?)(\b(?:1[2-9]\d{2}|20[0-2]\d)\b)",
            uri,
        ):
            year = int(m.group(1))
            if 1200 <= year <= 2026:
                return year
        # Fallback: first valid year
        return int(matches[0])
    return None


def _try_number_before_monarch(uri: str) -> int | None:
    """Strategy 6: Regnal with session number before monarch.

    Handles cases where the session number precedes the monarch name,
    which the earlier strategies miss because they look for monarch first.

    Catches:
      33 Vict.           → Victoria session 33
      5 Edw. 7. cxl     → Edward VII session 5
      36-37 Vict         → Victoria session 36
      1 Edw. 8.          → Edward VIII session 1
      30Vict.c.8         → Victoria session 30 (concatenated)
      28-vict-cap-xcix   → Victoria session 28 (slug style)
    """
    pattern = re.compile(
        r"(\d+)"                                  # session "33" or "36"
        r"(?:\s*[-&]\s*\d+)?"                     # optional second session "-37" or "& 37"
        r"\s*[-_.]?\s*"                           # separator
        r"([A-Za-z]{3,})\.?\s*"                   # monarch "Vict" or "Edw"
        r"[-_.]?(\d+)?",                          # optional monarch number "7" (allow dash separator)
        re.IGNORECASE,
    )
    for match in pattern.finditer(uri):
        session_str, monarch_name, monarch_num = match.groups()
        lookup = monarch_name.rstrip(".")
        if monarch_num:
            lookup = f"{lookup}{monarch_num}"
        monarch_info = _resolve_monarch(lookup)
        if monarch_info:
            _, reign_start, reign_end = monarch_info
            try:
                session = int(session_str)
                if 1 <= session <= 70:
                    year = _compute_year(reign_start, reign_end, session)
                    if year:
                        return year
            except ValueError:
                pass
    return None


def _try_embedded_year(uri: str) -> int | None:
    """Strategy 7: Extract year embedded in Act names, local/ paths, and [UNCLEAR:] text.

    Catches patterns where years are part of underscored/camelCase Act names
    rather than standalone word-boundary-delimited tokens:
      [UNCLEAR: Liverpool_Sanitary_Amendment_Act_1854_Cap.xv]
      [UNCLEAR: Huddersfield_Corporation_Act_1897_Ch_xxvi]
      local/Calne_Railway_Act_1860_Cap.xi
      local/Metropolitan_District_Railway_Act_1881_c.86
      Medway_Conservancy_Act_1881_ch.clxxiv

    Differs from Strategy 5 (_try_broad_year) by stripping [UNCLEAR:] wrappers
    and using non-word-boundary year matching.
    """
    # Strip [UNCLEAR: ...] wrapper to get at the content inside
    inner = uri
    unclear_match = re.search(r"\[UNCLEAR:\s*(.*?)\]?$", uri)
    if unclear_match:
        inner = unclear_match.group(1)

    # Look for year in Act_Name_YYYY or ActNameYYYY patterns
    matches = re.findall(r"(1[2-9]\d{2})", inner)
    if len(matches) == 1:
        year = int(matches[0])
        if 1200 <= year <= 2026:
            return year
    elif len(matches) > 1:
        # Prefer year after "Act" or before "Ch"/"Cap"/"c."
        for m in re.finditer(r"Act[_\s]*(1[2-9]\d{2})", inner):
            return int(m.group(1))
        return int(matches[0])
    return None


def tier1_regex_parse(legislation_id: str) -> tuple[int | None, str]:
    """Apply all Tier 1 regex strategies in order.

    Returns (year, strategy_name) or (None, "none").
    """
    strategies = [
        ("explicit_year", _try_explicit_year),
        ("regnal_separators", _try_regnal_with_separators),
        ("combined_reign", _try_combined_reign),
        ("freetext_monarch", _try_freetext_monarch),
        ("broad_year", _try_broad_year),
        ("number_before_monarch", _try_number_before_monarch),
        ("embedded_year", _try_embedded_year),
    ]
    for name, func in strategies:
        year = func(legislation_id)
        if year is not None:
            return year, name
    return None, "none"


# ── Tier 2: LLM-based parsing ────────────────────────────────────────────

def _get_llm_client() -> AzureOpenAI:
    """Create Azure OpenAI client for LLM year recovery."""
    return AzureOpenAI(
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version="2025-03-01-preview",
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    )


def _call_llm_batch(
    client: AzureOpenAI,
    uris: list[str],
    model: str = "gpt-5-nano",
) -> dict[str, tuple[int | None, str]]:
    """Send a batch of URIs to the LLM and parse year responses.

    Returns dict mapping URI → (year, confidence).
    """
    deployment = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT", model)

    uri_list = "\n".join(f"- {uri}" for uri in uris)
    user_prompt = f"Determine the calendar year for each legislation URI:\n\n{uri_list}"

    try:
        response = client.responses.create(
            model=deployment,
            instructions=LLM_SYSTEM_PROMPT,
            input=user_prompt,
            reasoning={"effort": "medium"},
        )

        raw_text = response.output_text.strip()
        # Strip markdown code fences if present
        if raw_text.startswith("```"):
            raw_text = re.sub(r"^```(?:json)?\n?", "", raw_text)
            raw_text = re.sub(r"\n?```$", "", raw_text)

        results = json.loads(raw_text)
        parsed = {}
        for item in results:
            uri = item.get("uri", "")
            year = item.get("year")
            confidence = item.get("confidence", "low")

            # Validate year
            if year is not None:
                if not isinstance(year, int) or year < 1200 or year > 2026:
                    year = None
                    confidence = "low"

            parsed[uri] = (year, confidence)

        return parsed

    except json.JSONDecodeError as e:
        logger.warning(f"LLM returned invalid JSON: {e}")
        return {uri: (None, "error") for uri in uris}
    except Exception as e:
        logger.warning(f"LLM batch failed: {e}")
        return {uri: (None, "error") for uri in uris}


def tier2_llm_parse(
    uris: list[str],
    stats: dict,
    *,
    qdrant_client=None,
    collection: str = "",
    apply: bool = False,
    id_map: dict | None = None,
) -> dict[str, int]:
    """Run Tier 2 LLM parsing on a list of URIs.

    When apply=True and qdrant_client is provided, writes corrections to Qdrant
    continuously as each LLM batch completes (no buffering).

    Returns dict mapping URI → recovered year (only high/medium confidence).
    """
    if not uris:
        return {}

    client = _get_llm_client()
    deployment = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT", "gpt-5-nano")
    console.print(f"\n[bold]Tier 2: LLM Recovery[/bold] ({len(uris):,} URIs, model={deployment})")

    # Split into batches
    batches = [uris[i : i + LLM_BATCH_SIZE] for i in range(0, len(uris), LLM_BATCH_SIZE)]
    recovered = {}
    pending_ops = []

    def _flush_ops(ops, wait=False):
        """Write pending operations to Qdrant."""
        if not ops or not apply or not qdrant_client:
            return
        try:
            batch_ops = list(ops)
            _retry_with_backoff(
                "Tier2 batch update",
                lambda: qdrant_client.batch_update_points(
                    collection_name=collection,
                    update_operations=batch_ops,
                    wait=wait,
                ),
            )
            stats["records_fixed"] += len(batch_ops)
            stats["batches_sent"] += 1
        except Exception as e:
            logger.error(f"Tier2 batch update failed: {e}")
            stats["errors"] += len(ops)

    with Progress(console=console) as progress:
        task = progress.add_task("LLM batches", total=len(batches))

        with ThreadPoolExecutor(max_workers=LLM_MAX_WORKERS) as executor:
            future_to_batch = {
                executor.submit(_call_llm_batch, client, batch): batch
                for batch in batches
            }

            for future in as_completed(future_to_batch):
                batch = future_to_batch[future]
                stats["llm_batches_sent"] += 1
                try:
                    results = future.result()
                    for uri, (year, confidence) in results.items():
                        if confidence == "error":
                            stats["llm_errors"] += 1
                        elif confidence == "low":
                            stats["llm_low_confidence"] += 1
                        elif year is not None:
                            recovered[uri] = year
                            if confidence == "high":
                                stats["llm_high_confidence"] += 1
                            else:
                                stats["llm_medium_confidence"] += 1

                            # Build Qdrant operation immediately
                            if id_map and uri in id_map:
                                point_id = id_map[uri]
                                pending_ops.append(
                                    models.SetPayloadOperation(
                                        set_payload=models.SetPayload(
                                            payload={"legislation_year": year},
                                            points=[point_id],
                                        )
                                    )
                                )
                except Exception as e:
                    logger.error(f"LLM batch exception: {e}")
                    stats["llm_errors"] += len(batch)

                # Flush to Qdrant every OPERATIONS_BATCH_SIZE ops
                if len(pending_ops) >= OPERATIONS_BATCH_SIZE:
                    _flush_ops(pending_ops)
                    pending_ops = []

                progress.update(task, advance=1)

    # Flush remaining
    if pending_ops:
        _flush_ops(pending_ops, wait=True)

    return recovered


# ── Main script ───────────────────────────────────────────────────────────

def fix_null_years(
    client,
    apply: bool = False,
    tier1_only: bool = False,
    tier2_only: bool = False,
    scroll_batch_size: int = DEFAULT_SCROLL_BATCH_SIZE,
) -> dict:
    """Recover null legislation_year values using regex + LLM."""
    collection = LEGISLATION_SECTION_COLLECTION
    console.rule(f"[bold]{collection}[/bold]")

    stats = {
        "total_null": 0,
        "tier1_explicit_year": 0,
        "tier1_regnal_separators": 0,
        "tier1_combined_reign": 0,
        "tier1_freetext_monarch": 0,
        "tier1_broad_year": 0,
        "tier1_number_before_monarch": 0,
        "tier1_embedded_year": 0,
        "tier1_total": 0,
        "tier2_needed": 0,
        "llm_batches_sent": 0,
        "llm_high_confidence": 0,
        "llm_medium_confidence": 0,
        "llm_low_confidence": 0,
        "llm_errors": 0,
        "tier2_total": 0,
        "total_recovered": 0,
        "remaining_null": 0,
        "records_fixed": 0,
        "batches_sent": 0,
        "errors": 0,
    }

    # Scroll only null-year sections using IsNullCondition
    null_year_filter = models.Filter(
        must=[
            models.IsNullCondition(
                is_null=models.PayloadField(key="legislation_year"),
            )
        ]
    )

    console.print("Scrolling null-year sections...")

    # Collect all null-year records
    all_points: list[tuple[str | int, str]] = []  # (point_id, legislation_id)
    offset = None

    with Progress(console=console) as progress:
        task = progress.add_task("Scrolling", total=None)

        while True:
            results, next_offset = _retry_with_backoff(
                "Scroll",
                lambda: client.scroll(
                    collection_name=collection,
                    limit=scroll_batch_size,
                    offset=offset,
                    scroll_filter=null_year_filter,
                    with_payload=READ_FIELDS,
                    with_vectors=False,
                ),
            )

            if not results:
                break

            for point in results:
                legislation_id = point.payload.get("legislation_id")
                if legislation_id:
                    all_points.append((point.id, legislation_id))

            progress.update(task, completed=len(all_points))

            offset = next_offset
            if offset is None:
                break

    stats["total_null"] = len(all_points)
    console.print(f"Found [bold]{len(all_points):,}[/bold] null-year sections\n")

    if not all_points:
        console.print("[green]No null-year sections found — nothing to do[/green]")
        return stats

    # ── Tier 1: Regex ─────────────────────────────────────────────────
    corrections: dict[str | int, int] = {}  # point_id → year
    tier2_candidates: list[tuple[str | int, str]] = []  # (point_id, legislation_id)

    if not tier2_only:
        console.print("[bold]Tier 1: Regex Recovery[/bold]")

        with Progress(console=console) as progress:
            task = progress.add_task("Regex parsing", total=len(all_points))

            for point_id, legislation_id in all_points:
                year, strategy = tier1_regex_parse(legislation_id)
                if year is not None:
                    corrections[point_id] = year
                    stats[f"tier1_{strategy}"] += 1
                    stats["tier1_total"] += 1
                else:
                    tier2_candidates.append((point_id, legislation_id))

                progress.update(task, advance=1)

        console.print(f"  Explicit year:        {stats['tier1_explicit_year']:,}")
        console.print(f"  Regnal separators:    {stats['tier1_regnal_separators']:,}")
        console.print(f"  Combined reign:       {stats['tier1_combined_reign']:,}")
        console.print(f"  Freetext monarch:     {stats['tier1_freetext_monarch']:,}")
        console.print(f"  Broad year:           {stats['tier1_broad_year']:,}")
        console.print(f"  Number before monarch: {stats['tier1_number_before_monarch']:,}")
        console.print(f"  Embedded year:         {stats['tier1_embedded_year']:,}")
        console.print(
            f"  [bold]Total Tier 1:      {stats['tier1_total']:,}[/bold] "
            f"({stats['tier1_total'] / len(all_points) * 100:.1f}%)"
        )
    else:
        tier2_candidates = list(all_points)

    # ── Tier 2: LLM ──────────────────────────────────────────────────
    stats["tier2_needed"] = len(tier2_candidates)

    if not tier1_only and tier2_candidates:
        tier2_uris = [lid for _, lid in tier2_candidates]
        tier2_id_map = {lid: pid for pid, lid in tier2_candidates}

        llm_results = tier2_llm_parse(
            tier2_uris,
            stats,
            qdrant_client=client if apply else None,
            collection=collection,
            apply=apply,
            id_map=tier2_id_map,
        )

        for uri, year in llm_results.items():
            point_id = tier2_id_map.get(uri)
            if point_id is not None:
                corrections[point_id] = year

        stats["tier2_total"] = stats["llm_high_confidence"] + stats["llm_medium_confidence"]
        console.print(f"\n  High confidence:   {stats['llm_high_confidence']:,}")
        console.print(f"  Medium confidence: {stats['llm_medium_confidence']:,}")
        console.print(f"  Low (skipped):     {stats['llm_low_confidence']:,}")
        console.print(f"  Errors:            {stats['llm_errors']:,}")
        console.print(
            f"  [bold]Total Tier 2:      {stats['tier2_total']:,}[/bold]"
        )

    stats["total_recovered"] = len(corrections)
    stats["remaining_null"] = stats["total_null"] - stats["total_recovered"]

    # ── Apply corrections (Tier 1 only — Tier 2 writes continuously) ──
    # Build set of point_ids already written by Tier 2
    tier2_written_ids = set()
    if apply and not tier1_only and tier2_candidates:
        tier2_written_ids = {pid for pid, _ in tier2_candidates if pid in corrections}

    tier1_corrections = {pid: yr for pid, yr in corrections.items() if pid not in tier2_written_ids}

    if apply and tier1_corrections:
        console.print(f"\n[bold]Applying {len(tier1_corrections):,} Tier 1 corrections...[/bold]")
        pending_operations = []

        with Progress(console=console) as progress:
            task = progress.add_task("Applying", total=len(tier1_corrections))

            for point_id, year in tier1_corrections.items():
                operation = models.SetPayloadOperation(
                    set_payload=models.SetPayload(
                        payload={"legislation_year": year},
                        points=[point_id],
                    )
                )
                pending_operations.append(operation)

                if len(pending_operations) >= OPERATIONS_BATCH_SIZE:
                    try:
                        ops = pending_operations
                        _retry_with_backoff(
                            "Batch update",
                            lambda: client.batch_update_points(
                                collection_name=collection,
                                update_operations=ops,
                                wait=False,
                            ),
                        )
                        stats["records_fixed"] += len(pending_operations)
                        stats["batches_sent"] += 1
                    except Exception as e:
                        logger.error(f"Batch update failed: {e}")
                        stats["errors"] += len(pending_operations)
                    pending_operations = []
                    progress.update(task, completed=stats["records_fixed"])

        # Flush remaining
        if pending_operations:
            try:
                ops = pending_operations
                _retry_with_backoff(
                    "Final batch update",
                    lambda: client.batch_update_points(
                        collection_name=collection,
                        update_operations=ops,
                        wait=True,
                    ),
                )
                stats["records_fixed"] += len(pending_operations)
                stats["batches_sent"] += 1
            except Exception as e:
                logger.error(f"Final batch update failed: {e}")
                stats["errors"] += len(pending_operations)

    # ── Summary ───────────────────────────────────────────────────────
    mode = "APPLIED" if apply else "DRY RUN"
    pct = (stats["total_recovered"] / stats["total_null"] * 100) if stats["total_null"] else 0
    summary_stats = {
        "Mode": mode,
        "Total null-year sections": f"{stats['total_null']:,}",
        "Tier 1 recovered": f"{stats['tier1_total']:,}",
        "Tier 2 recovered": f"{stats['tier2_total']:,}",
        "Total recovered": f"{stats['total_recovered']:,} ({pct:.1f}%)",
        "Remaining null": f"{stats['remaining_null']:,}",
    }
    if apply:
        summary_stats["Records fixed"] = f"{stats['records_fixed']:,}"
        summary_stats["Batches sent"] = f"{stats['batches_sent']:,}"
        summary_stats["Errors"] = f"{stats['errors']:,}"

    print_summary("Null-Year Recovery", summary_stats, success=stats["errors"] == 0)

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Recover null legislation_year values using regex + LLM fallback"
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually apply fixes (default is dry run)",
    )
    parser.add_argument(
        "--tier1-only",
        action="store_true",
        help="Only run Tier 1 regex parsing (no LLM calls)",
    )
    parser.add_argument(
        "--tier2-only",
        action="store_true",
        help="Only run Tier 2 LLM parsing (skip regex)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_SCROLL_BATCH_SIZE,
        help=f"Batch size for scrolling (default: {DEFAULT_SCROLL_BATCH_SIZE})",
    )
    args = parser.parse_args()

    if args.tier1_only and args.tier2_only:
        console.print("[red]Cannot specify both --tier1-only and --tier2-only[/red]")
        sys.exit(1)

    setup_logging()

    tier_mode = "Tier 1 only" if args.tier1_only else ("Tier 2 only" if args.tier2_only else "Tier 1 + Tier 2")
    print_header(
        "Null-Year Recovery",
        mode="APPLY" if args.apply else "DRY RUN",
        details={
            "Strategy": tier_mode,
            "Collection": LEGISLATION_SECTION_COLLECTION,
            "Tier 1": "Regex (4 strategies)",
            "Tier 2": "LLM (gpt-5-nano, medium reasoning)",
        },
    )

    client = get_qdrant_client()

    stats = fix_null_years(
        client,
        apply=args.apply,
        tier1_only=args.tier1_only,
        tier2_only=args.tier2_only,
        scroll_batch_size=args.batch_size,
    )

    if not args.apply and stats["total_recovered"] > 0:
        console.print(
            f"\n[yellow]Run with --apply to fix {stats['total_recovered']:,} records[/yellow]"
        )


if __name__ == "__main__":
    main()
