#!/usr/bin/env python
"""
Recover legislation_year for sections where deterministic parsing returned null.

These are pre-1963 legislation with nonstandard regnal year URIs generated by
LLM-based OCR — hallucinations, inconsistent formatting, freetext monarch names.

TWO-TIER APPROACH:
  Tier 1 (deterministic): regnal.parse_legislation_year() — 10 strategies covering
    standard URIs, regnal years with nonstandard separators, freetext citations,
    combined reign references, embedded years, and short title text extraction.
    See src/lex/legislation/regnal.py for the full strategy list.

  Tier 2 (LLM): Azure OpenAI gpt-5-nano with monarch table in system prompt.
    Batches 25 URIs per call, medium reasoning effort. Writes to Qdrant
    continuously as batches complete. Only for genuinely ambiguous records.

Results (March 2026):
  Original null-year: 213,356 sections
  Tier 1 (deterministic): ~204,400 recovered
  Tier 2 (LLM):           ~4,889 recovered
  Remaining null:          ~3,996 (genuinely unrecoverable)
  Final coverage:          ~99.81%

Usage:
    uv run python scripts/maintenance/fix_null_years.py                        # dry run
    uv run python scripts/maintenance/fix_null_years.py --apply                # apply all
    uv run python scripts/maintenance/fix_null_years.py --apply --tier1-only   # deterministic only
    uv run python scripts/maintenance/fix_null_years.py --apply --tier2-only   # LLM only
"""

import argparse
import json
import logging
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).parent.parent))  # scripts/ directory

from dotenv import load_dotenv

load_dotenv(dotenv_path=Path(__file__).parent.parent.parent / ".env", override=True)

from _console import console, print_header, print_summary, setup_logging  # noqa: E402
from openai import AzureOpenAI  # noqa: E402
from qdrant_client import models  # noqa: E402
from rich.progress import Progress  # noqa: E402

from lex.core.qdrant_client import get_qdrant_client  # noqa: E402
from lex.legislation.regnal import parse_legislation_year  # noqa: E402
from lex.settings import LEGISLATION_SECTION_COLLECTION  # noqa: E402

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────

OPERATIONS_BATCH_SIZE = 200
DEFAULT_SCROLL_BATCH_SIZE = 500
MAX_RETRIES = 5
BASE_BACKOFF = 2.0
LLM_BATCH_SIZE = 25
LLM_MAX_WORKERS = 5

# Payload fields to read from each point
READ_FIELDS = ["legislation_id", "legislation_year"]
TEXT_FIELDS = ["legislation_id", "legislation_year", "text"]


# ── LLM system prompt ────────────────────────────────────────────────────

LLM_SYSTEM_PROMPT = """You are a UK legal citation expert. Given legislation URIs \
from legislation.gov.uk, determine the calendar year each Act was enacted.

UK legislation before 1963 uses regnal years — the year of a monarch's \
reign. For example, "5 & 6 Vict" means sessions 5-6 of Queen Victoria's \
reign (which started 1837), so 5 Vict = 1841 (1837 + 5 - 1 = 1841).

To calculate: year = monarch_reign_start + first_session_number - 1

Monarch reign start years (canonical abbreviation = start year):
Hen3=1216, Edw1=1272, Edw2=1307, Edw3=1327, Ric2=1377, Hen4=1399, \
Hen5=1413, Hen6=1422, Edw4=1461, Ric3=1483, Hen7=1485, Hen8=1509, \
Edw6=1547, Mar1=1553, Eliz1=1558, Jas1=1603, Cha1=1625, Cha2=1660, \
WillandMar=1689, Will3=1694, Ann=1702, Geo1=1714, Geo2=1727, \
Geo3=1760, Geo4=1820, Will4=1830, Vict=1837, Edw7=1901, Geo5=1910, \
Edw8=1936, Geo6=1936, Eliz2=1952.

Common patterns:
- /ukpga/Vict/44-45/12 → Victoria session 44 → 1837+44-1 = 1880
- /ukpga/Geo3/39-40/67 → George III session 39 → 1760+39-1 = 1798
- /ukla/Edw7/9/29 → Edward VII session 9 → 1901+9-1 = 1909
- Combined reigns: /Edw8and1Geo6/1/100 → George VI session 1 → 1936

Some URIs contain OCR artefacts like [UNCLEAR:...] — use surrounding \
context to infer the most likely legislation and year. Return null for \
year only if genuinely unrecoverable.

IMPORTANT: Respond with ONLY a JSON array, no other text. Each element:
{"uri": "<the original uri>", "year": <integer or null>, "confidence": "high"|"medium"|"low"}"""


# ── Retry helper ──────────────────────────────────────────────────────────


def _is_retryable(error: Exception) -> bool:
    error_str = str(error).lower()
    return any(term in error_str for term in ["timed out", "timeout", "connection"])


def _retry_with_backoff(operation_name: str, operation, max_retries=MAX_RETRIES):
    for attempt in range(max_retries):
        try:
            return operation()
        except Exception as e:
            if attempt == max_retries - 1 or not _is_retryable(e):
                raise
            backoff = BASE_BACKOFF * (2**attempt)
            logger.warning(
                f"{operation_name} timeout (attempt {attempt + 1}/{max_retries}), "
                f"retrying in {backoff:.0f}s..."
            )
            time.sleep(backoff)


# ── Tier 1: Deterministic parsing ─────────────────────────────────────────


def tier1_deterministic_parse(legislation_id: str) -> int | None:
    """Apply all deterministic strategies via regnal.parse_legislation_year().

    Returns year or None.
    """
    return parse_legislation_year(legislation_id)


def tier1_deterministic_parse_with_text(legislation_id: str, text: str | None = None) -> int | None:
    """Deterministic parse including text-based short title extraction."""
    return parse_legislation_year(legislation_id, text=text)


# ── Tier 2: LLM-based parsing ────────────────────────────────────────────


def _get_llm_client() -> AzureOpenAI:
    """Create Azure OpenAI client for LLM year recovery."""
    return AzureOpenAI(
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version="2025-03-01-preview",
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    )


def _call_llm_batch(
    client: AzureOpenAI,
    uris: list[str],
    model: str = "gpt-5-nano",
) -> dict[str, tuple[int | None, str]]:
    """Send a batch of URIs to the LLM and parse year responses.

    Returns dict mapping URI → (year, confidence).
    """
    deployment = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT", model)

    uri_list = "\n".join(f"- {uri}" for uri in uris)
    user_prompt = f"Determine the calendar year for each legislation URI:\n\n{uri_list}"

    try:
        response = client.responses.create(
            model=deployment,
            instructions=LLM_SYSTEM_PROMPT,
            input=user_prompt,
            reasoning={"effort": "medium"},
        )

        raw_text = response.output_text.strip()
        if raw_text.startswith("```"):
            raw_text = re.sub(r"^```(?:json)?\n?", "", raw_text)
            raw_text = re.sub(r"\n?```$", "", raw_text)

        results = json.loads(raw_text)
        parsed = {}
        for item in results:
            uri = item.get("uri", "")
            year = item.get("year")
            confidence = item.get("confidence", "low")

            if year is not None:
                if not isinstance(year, int) or year < 1200 or year > 2026:
                    year = None
                    confidence = "low"

            parsed[uri] = (year, confidence)

        return parsed

    except json.JSONDecodeError as e:
        logger.warning(f"LLM returned invalid JSON: {e}")
        return {uri: (None, "error") for uri in uris}
    except Exception as e:
        logger.warning(f"LLM batch failed: {e}")
        return {uri: (None, "error") for uri in uris}


def tier2_llm_parse(
    uris: list[str],
    stats: dict,
    *,
    qdrant_client=None,
    collection: str = "",
    apply: bool = False,
    id_map: dict | None = None,
) -> dict[str, int]:
    """Run Tier 2 LLM parsing on a list of URIs.

    When apply=True and qdrant_client is provided, writes corrections to Qdrant
    continuously as each LLM batch completes (no buffering).

    Returns dict mapping URI → recovered year (only high/medium confidence).
    """
    if not uris:
        return {}

    client = _get_llm_client()
    deployment = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT", "gpt-5-nano")
    console.print(f"\n[bold]Tier 2: LLM Recovery[/bold] ({len(uris):,} URIs, model={deployment})")

    batches = [uris[i : i + LLM_BATCH_SIZE] for i in range(0, len(uris), LLM_BATCH_SIZE)]
    recovered = {}
    pending_ops = []

    def _flush_ops(ops, wait=False):
        """Write pending operations to Qdrant."""
        if not ops or not apply or not qdrant_client:
            return
        try:
            batch_ops = list(ops)
            _retry_with_backoff(
                "Tier2 batch update",
                lambda: qdrant_client.batch_update_points(
                    collection_name=collection,
                    update_operations=batch_ops,
                    wait=wait,
                ),
            )
            stats["records_fixed"] += len(batch_ops)
            stats["batches_sent"] += 1
        except Exception as e:
            logger.error(f"Tier2 batch update failed: {e}")
            stats["errors"] += len(ops)

    with Progress(console=console) as progress:
        task = progress.add_task("LLM batches", total=len(batches))

        with ThreadPoolExecutor(max_workers=LLM_MAX_WORKERS) as executor:
            future_to_batch = {
                executor.submit(_call_llm_batch, client, batch): batch for batch in batches
            }

            for future in as_completed(future_to_batch):
                batch = future_to_batch[future]
                stats["llm_batches_sent"] += 1
                try:
                    results = future.result()
                    for uri, (year, confidence) in results.items():
                        if confidence == "error":
                            stats["llm_errors"] += 1
                        elif confidence == "low":
                            stats["llm_low_confidence"] += 1
                        elif year is not None:
                            recovered[uri] = year
                            if confidence == "high":
                                stats["llm_high_confidence"] += 1
                            else:
                                stats["llm_medium_confidence"] += 1

                            if id_map and uri in id_map:
                                point_id = id_map[uri]
                                pending_ops.append(
                                    models.SetPayloadOperation(
                                        set_payload=models.SetPayload(
                                            payload={"legislation_year": year},
                                            points=[point_id],
                                        )
                                    )
                                )
                except Exception as e:
                    logger.error(f"LLM batch exception: {e}")
                    stats["llm_errors"] += len(batch)

                if len(pending_ops) >= OPERATIONS_BATCH_SIZE:
                    _flush_ops(pending_ops)
                    pending_ops = []

                progress.update(task, advance=1)

    if pending_ops:
        _flush_ops(pending_ops, wait=True)

    return recovered


# ── Text-based recovery (deterministic, uses Tier 1 with text) ────────────


def text_based_recovery(
    client,
    remaining_points: list[tuple[str | int, str]],
    collection: str,
    scroll_batch_size: int,
    stats: dict,
    apply: bool = False,
) -> dict[str | int, int]:
    """Extract years from section text content (short title citations).

    Groups sections by legislation_id, finds short title years from any section
    in the group, then applies the year to ALL sections of that group.

    This uses strategy 10 of parse_legislation_year() (text parameter).

    Returns dict mapping point_id → recovered year.
    """
    if not remaining_points:
        return {}

    console.print(f"\n[bold]Text-Based Recovery[/bold] ({len(remaining_points):,} sections)")

    # Group point IDs by legislation_id
    leg_id_to_points: dict[str, list[str | int]] = {}
    for point_id, legislation_id in remaining_points:
        leg_id_to_points.setdefault(legislation_id, []).append(point_id)

    console.print(f"  Unique Acts: {len(leg_id_to_points):,}")

    # Scroll remaining null-year sections WITH text payload
    leg_id_to_year: dict[str, int] = {}

    null_year_filter = models.Filter(
        must=[
            models.IsNullCondition(
                is_null=models.PayloadField(key="legislation_year"),
            )
        ]
    )

    offset = None
    sections_scanned = 0

    with Progress(console=console) as progress:
        task = progress.add_task("Scanning text", total=len(remaining_points))

        while True:
            results, next_offset = _retry_with_backoff(
                "Text scroll",
                lambda: client.scroll(
                    collection_name=collection,
                    limit=scroll_batch_size,
                    offset=offset,
                    scroll_filter=null_year_filter,
                    with_payload=TEXT_FIELDS,
                    with_vectors=False,
                ),
            )

            if not results:
                break

            for point in results:
                legislation_id = point.payload.get("legislation_id", "")
                if legislation_id in leg_id_to_year:
                    continue
                text = point.payload.get("text", "")
                if text:
                    year = parse_legislation_year(legislation_id, text=text)
                    if year:
                        leg_id_to_year[legislation_id] = year

            sections_scanned += len(results)
            progress.update(task, completed=sections_scanned)

            offset = next_offset
            if offset is None:
                break

    # Build corrections: apply each Act's year to ALL its sections
    corrections: dict[str | int, int] = {}
    for legislation_id, year in leg_id_to_year.items():
        for point_id in leg_id_to_points.get(legislation_id, []):
            corrections[point_id] = year

    stats["text_acts_with_year"] = len(leg_id_to_year)
    stats["text_total"] = len(corrections)
    console.print(f"  Acts with short title year: {len(leg_id_to_year):,}")
    console.print(f"  [bold]Total text-based: {len(corrections):,}[/bold]")

    # Apply corrections
    if apply and corrections:
        console.print(f"\n  Applying {len(corrections):,} text-based corrections...")
        pending_ops = []

        for point_id, year in corrections.items():
            pending_ops.append(
                models.SetPayloadOperation(
                    set_payload=models.SetPayload(
                        payload={"legislation_year": year},
                        points=[point_id],
                    )
                )
            )

            if len(pending_ops) >= OPERATIONS_BATCH_SIZE:
                ops = list(pending_ops)
                _retry_with_backoff(
                    "Text batch update",
                    lambda: client.batch_update_points(
                        collection_name=collection,
                        update_operations=ops,
                        wait=False,
                    ),
                )
                stats["records_fixed"] += len(pending_ops)
                stats["batches_sent"] += 1
                pending_ops = []

        if pending_ops:
            ops = list(pending_ops)
            _retry_with_backoff(
                "Text final batch",
                lambda: client.batch_update_points(
                    collection_name=collection,
                    update_operations=ops,
                    wait=True,
                ),
            )
            stats["records_fixed"] += len(pending_ops)
            stats["batches_sent"] += 1

    return corrections


# ── Main script ───────────────────────────────────────────────────────────


def fix_null_years(
    client,
    apply: bool = False,
    tier1_only: bool = False,
    tier2_only: bool = False,
    scroll_batch_size: int = DEFAULT_SCROLL_BATCH_SIZE,
) -> dict:
    """Recover null legislation_year values using deterministic parsing + LLM fallback."""
    collection = LEGISLATION_SECTION_COLLECTION
    console.rule(f"[bold]{collection}[/bold]")

    stats = {
        "total_null": 0,
        "tier1_total": 0,
        "tier2_needed": 0,
        "llm_batches_sent": 0,
        "llm_high_confidence": 0,
        "llm_medium_confidence": 0,
        "llm_low_confidence": 0,
        "llm_errors": 0,
        "tier2_total": 0,
        "text_acts_with_year": 0,
        "text_total": 0,
        "total_recovered": 0,
        "remaining_null": 0,
        "records_fixed": 0,
        "batches_sent": 0,
        "errors": 0,
    }

    # Scroll only null-year sections using IsNullCondition
    null_year_filter = models.Filter(
        must=[
            models.IsNullCondition(
                is_null=models.PayloadField(key="legislation_year"),
            )
        ]
    )

    console.print("Scrolling null-year sections...")

    all_points: list[tuple[str | int, str]] = []  # (point_id, legislation_id)
    offset = None

    with Progress(console=console) as progress:
        task = progress.add_task("Scrolling", total=None)

        while True:
            results, next_offset = _retry_with_backoff(
                "Scroll",
                lambda: client.scroll(
                    collection_name=collection,
                    limit=scroll_batch_size,
                    offset=offset,
                    scroll_filter=null_year_filter,
                    with_payload=READ_FIELDS,
                    with_vectors=False,
                ),
            )

            if not results:
                break

            for point in results:
                legislation_id = point.payload.get("legislation_id")
                if legislation_id:
                    all_points.append((point.id, legislation_id))

            progress.update(task, completed=len(all_points))

            offset = next_offset
            if offset is None:
                break

    stats["total_null"] = len(all_points)
    console.print(f"Found [bold]{len(all_points):,}[/bold] null-year sections\n")

    if not all_points:
        console.print("[green]No null-year sections found — nothing to do[/green]")
        return stats

    # ── Tier 1: Deterministic ──────────────────────────────────────────
    corrections: dict[str | int, int] = {}  # point_id → year
    tier2_candidates: list[tuple[str | int, str]] = []  # (point_id, legislation_id)

    if not tier2_only:
        console.print("[bold]Tier 1: Deterministic Recovery[/bold]")

        with Progress(console=console) as progress:
            task = progress.add_task("Parsing", total=len(all_points))

            for point_id, legislation_id in all_points:
                year = tier1_deterministic_parse(legislation_id)
                if year is not None:
                    corrections[point_id] = year
                    stats["tier1_total"] += 1
                else:
                    tier2_candidates.append((point_id, legislation_id))

                progress.update(task, advance=1)

        console.print(
            f"  [bold]Total Tier 1:      {stats['tier1_total']:,}[/bold] "
            f"({stats['tier1_total'] / len(all_points) * 100:.1f}%)"
        )
    else:
        tier2_candidates = list(all_points)

    # ── Tier 2: LLM ──────────────────────────────────────────────────
    stats["tier2_needed"] = len(tier2_candidates)

    if not tier1_only and tier2_candidates:
        tier2_uris = [lid for _, lid in tier2_candidates]
        tier2_id_map = {lid: pid for pid, lid in tier2_candidates}

        llm_results = tier2_llm_parse(
            tier2_uris,
            stats,
            qdrant_client=client if apply else None,
            collection=collection,
            apply=apply,
            id_map=tier2_id_map,
        )

        for uri, year in llm_results.items():
            point_id = tier2_id_map.get(uri)
            if point_id is not None:
                corrections[point_id] = year

        stats["tier2_total"] = stats["llm_high_confidence"] + stats["llm_medium_confidence"]
        console.print(f"\n  High confidence:   {stats['llm_high_confidence']:,}")
        console.print(f"  Medium confidence: {stats['llm_medium_confidence']:,}")
        console.print(f"  Low (skipped):     {stats['llm_low_confidence']:,}")
        console.print(f"  Errors:            {stats['llm_errors']:,}")
        console.print(f"  [bold]Total Tier 2:      {stats['tier2_total']:,}[/bold]")

    # ── Text-based recovery (deterministic, runs after LLM) ──────────
    if not tier1_only and not tier2_only:
        text_remaining = [(pid, lid) for pid, lid in tier2_candidates if pid not in corrections]
        if text_remaining:
            text_corrections = text_based_recovery(
                client,
                text_remaining,
                collection,
                scroll_batch_size,
                stats,
                apply=apply,
            )
            corrections.update(text_corrections)

    stats["total_recovered"] = len(corrections)
    stats["remaining_null"] = stats["total_null"] - stats["total_recovered"]

    # ── Apply corrections (Tier 1 only — Tier 2 writes continuously) ──
    tier2_written_ids = set()
    if apply and not tier1_only and tier2_candidates:
        tier2_written_ids = {pid for pid, _ in tier2_candidates if pid in corrections}

    tier1_corrections = {pid: yr for pid, yr in corrections.items() if pid not in tier2_written_ids}

    if apply and tier1_corrections:
        console.print(
            f"\n[bold]Applying {len(tier1_corrections):,} deterministic corrections...[/bold]"
        )
        pending_operations = []

        with Progress(console=console) as progress:
            task = progress.add_task("Applying", total=len(tier1_corrections))

            for point_id, year in tier1_corrections.items():
                operation = models.SetPayloadOperation(
                    set_payload=models.SetPayload(
                        payload={"legislation_year": year},
                        points=[point_id],
                    )
                )
                pending_operations.append(operation)

                if len(pending_operations) >= OPERATIONS_BATCH_SIZE:
                    try:
                        ops = pending_operations
                        _retry_with_backoff(
                            "Batch update",
                            lambda: client.batch_update_points(
                                collection_name=collection,
                                update_operations=ops,
                                wait=False,
                            ),
                        )
                        stats["records_fixed"] += len(pending_operations)
                        stats["batches_sent"] += 1
                    except Exception as e:
                        logger.error(f"Batch update failed: {e}")
                        stats["errors"] += len(pending_operations)
                    pending_operations = []
                    progress.update(task, completed=stats["records_fixed"])

        # Flush remaining
        if pending_operations:
            try:
                ops = pending_operations
                _retry_with_backoff(
                    "Final batch update",
                    lambda: client.batch_update_points(
                        collection_name=collection,
                        update_operations=ops,
                        wait=True,
                    ),
                )
                stats["records_fixed"] += len(pending_operations)
                stats["batches_sent"] += 1
            except Exception as e:
                logger.error(f"Final batch update failed: {e}")
                stats["errors"] += len(pending_operations)

    # ── Summary ───────────────────────────────────────────────────────
    mode = "APPLIED" if apply else "DRY RUN"
    pct = (stats["total_recovered"] / stats["total_null"] * 100) if stats["total_null"] else 0
    summary_stats = {
        "Mode": mode,
        "Total null-year sections": f"{stats['total_null']:,}",
        "Tier 1 (deterministic)": f"{stats['tier1_total']:,}",
        "Tier 2 (LLM)": f"{stats['tier2_total']:,}",
        "Text-based": f"{stats['text_total']:,}",
        "Total recovered": f"{stats['total_recovered']:,} ({pct:.1f}%)",
        "Remaining null": f"{stats['remaining_null']:,}",
    }
    if apply:
        summary_stats["Records fixed"] = f"{stats['records_fixed']:,}"
        summary_stats["Batches sent"] = f"{stats['batches_sent']:,}"
        summary_stats["Errors"] = f"{stats['errors']:,}"

    print_summary("Null-Year Recovery", summary_stats, success=stats["errors"] == 0)

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Recover null legislation_year values using deterministic + LLM"
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually apply fixes (default is dry run)",
    )
    parser.add_argument(
        "--tier1-only",
        action="store_true",
        help="Only run Tier 1 deterministic parsing (no LLM calls)",
    )
    parser.add_argument(
        "--tier2-only",
        action="store_true",
        help="Only run Tier 2 LLM parsing (skip deterministic)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_SCROLL_BATCH_SIZE,
        help=f"Batch size for scrolling (default: {DEFAULT_SCROLL_BATCH_SIZE})",
    )
    args = parser.parse_args()

    if args.tier1_only and args.tier2_only:
        console.print("[red]Cannot specify both --tier1-only and --tier2-only[/red]")
        sys.exit(1)

    setup_logging()

    if args.tier1_only:
        tier_mode = "Tier 1 only (deterministic)"
    elif args.tier2_only:
        tier_mode = "Tier 2 only (LLM)"
    else:
        tier_mode = "Tier 1 (deterministic) + Tier 2 (LLM) + text"

    print_header(
        "Null-Year Recovery",
        mode="APPLY" if args.apply else "DRY RUN",
        details={
            "Strategy": tier_mode,
            "Collection": LEGISLATION_SECTION_COLLECTION,
            "Tier 1": "Deterministic (10 strategies, regnal.py)",
            "Tier 2": "LLM (gpt-5-nano, medium reasoning)",
        },
    )

    client = get_qdrant_client()

    stats = fix_null_years(
        client,
        apply=args.apply,
        tier1_only=args.tier1_only,
        tier2_only=args.tier2_only,
        scroll_batch_size=args.batch_size,
    )

    if not args.apply and stats["total_recovered"] > 0:
        console.print(
            f"\n[yellow]Run with --apply to fix {stats['total_recovered']:,} records[/yellow]"
        )


if __name__ == "__main__":
    main()
